### ISSUE TITLE
Fails to locate some imported/inherited contracts in node_modules

### ISSUE THREAD

**Issue by coinfupanda** [paulrberg/multisol#14] opened 2021-08-20 10:49 UTC
**Problem**
multisol throws error: `Couldn't get an absolute path to the contract: "IERC165.sol"` when run in the create-react-app repo structure, using openzeppelin imports in the target contract.

In this case, `IERC165.sol` is not a direct import of the target contract - it is inherited by `IERC721.sol`, which is itself inherited by `ERC721.sol`.

**repo structure**
```
myProject
  /contracts
    /VerifyThisContract.sol
  /node_modules
  /...
```

**VerifyThisContract.sol header**
```
// File: VerifyThisContract.sol

pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721Pausable.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
```

**CLI to reproduce**
```
> cd c:/users/.../myProject
> multisol contracts/VerifyThisContract.sol
```

**Response**
`Couldn't get an absolute path to the contract: "IERC165.sol"`

**node_modules structure**
![image](https://user-images.githubusercontent.com/86688392/130222115-04245e82-e017-4ea5-8dda-96f734780408.png)

**Comment by PaulRBerg** [comment] 2021-08-20 10:57
Thank you ser! I will investigate this.

**Comment by ihorbond** [comment] 2022-03-03 04:38
getting the same error

**Comment by PaulRBerg** [comment] 2022-03-03 10:57
@ihorbond is your set-up exactly the same as @coinfupanda's? If not, could you add more details?

**Comment by ihorbond** [comment] 2022-03-03 20:19
@paulrberg yes exactly the same. I have NFT contract that loads up OZ dependencies and the nested one are erroring out in the same way

**Comment by PaulRBerg** [comment] 2022-03-03 21:25
I see. To be frank I won't have time to investigate this in the near future .. but if anyone does, PRs accepted :)

**Comment by ihorbond** [comment] 2022-03-04 22:38
I'm too dumb to pick up Rust lol

**Comment by PaulRBerg** [comment] 2024-01-01 07:43
Closing as a duplicate of https://github.com/PaulRBerg/multisol/issues/13.

**Closed as not planned by PaulRBerg** 2024-01-01 07:43 UTC
Labels: duplicate
